[project]
name = "portfolio"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "isort>=8.0.1",
]

[tool.mypy]
ignore_missing_imports = true
explicit_package_bases = true
mypy_path = "."
# Exclude the project root from mypy checks
exclude = ["priyanshu-sharma", "tests"]

[tool.isort]
profile = "black"

